package de.jk.spring.firsttrial.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.Length;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


@Entity
@Table(name="CUSTOMER")
//Swagger
@ApiModel(description = "Attributes single Customer")
public class CustomerEntity {
	

	@Id //Database
	@GeneratedValue(strategy = GenerationType.IDENTITY) //Database
	@ApiModelProperty(dataType = "java.lang.Long", notes  = "Data type = long, unique identifier generated by db. With new record set id=0", required = false, position = 1) //Swagger
	private Long id;
     
    @Column(name="first_name", nullable=false, length=255) //Database
    @NotNull //Input Validation
    @Size(min=0, max = 255) //Input Validation + Swagger Output
    @ApiModelProperty(required = true, dataType = "String", notes  = "first name of the customer", position = 2, example = "Harry") //Swagger
    private String firstName;
     
    @Column(name="last_name", nullable=false, length=255)
    @NotNull //Input Validation
    @Size(min=0, max = 255) //Input Validation + Swagger Output
    @ApiModelProperty(required = true, dataType = "String", notes  = "last name of the customer",  example = "Potter", position = 3) //Swagger
    
    private String lastName;
    //RFC 5321 for mail adress length
    @NotNull //Input Validation
    @Size(min=0, max = 320) //Input Validation + Swagger Output
    @Email //Input Validation
    @Column(name="email", nullable=false, length=320)
    @ApiModelProperty(required = true, dataType = "String", notes  = "last name of the customer, max. length=320 (RFC 3696), format: valid email format (must contain ... localpart(max. 64 chars)@hostname.topleveldomain(max 255 chars))",  example = "harry.potter@hogwarts.com", position = 4) //Swagger
    private String email;
     
    
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Override
    public String toString() {
        return "EmployeeEntity [id=" + id + ", firstName=" + firstName + 
                ", lastName=" + lastName + ", email=" + email   + "]";
    }

}
